name: tabadul
description: tabadul application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^9.1.0

  # Dependency injection
  get_it: ^8.0.3

  # Ui && Design
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.2.2
  flutter_zoom_drawer: ^3.1.1
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  animate_do: ^4.2.0

  #local Storage
  shared_preferences: ^2.2.0

  # Functional Programming
  dartz: ^0.10.1

  # Check your internet connection
  internet_connection_checker_plus: ^2.7.1

  get: ^4.6.5
  url_launcher: ^6.1.12
  image_picker: ^1.0.0
  sms_autofill: ^2.3.0

  # Networking
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.4.5

  # Change launcher icon app
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"
  image_path_ios: "assets/images/launcher_icon.png"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#464698"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons_images/
    - assets/images/departments/
    - assets/images/login_and_create_account/
    - assets/images/splash/
    - assets/images/on_boarding/

  fonts:
    - family: HelveticaLTArabic
      fonts:
        - asset: assets/fonts/HelveticaNeueLT-Arabic-75-Bold.ttf

    - family: HelveticaNeueLTRoman
      fonts:
        - asset: assets/fonts/HelveticaNeueLT-55-Roman-Bold.ttf
